export const CATEGORY_COLORS = [
  { name: "Green", hex: "#4CAF50" },
  { name: "Blue", hex: "#2196F3" },
  { name: "Pink", hex: "#E91E63" },
  { name: "Orange", hex: "#FF9800" },
  { name: "Purple", hex: "#9C27B0" },
  { name: "Red", hex: "#F44336" },
  { name: "Teal", hex: "#009688" },
  { name: "Indigo", hex: "#3F51B5" },
  { name: "Yellow", hex: "#FFEB3B" },
  { name: "Brown", hex: "#795548" },
  { name: "Gray", hex: "#9E9E9E" },
  { name: "Lime", hex: "#CDDC39" },
  { name: "Cyan", hex: "#00BCD4" },
  { name: "Deep Orange", hex: "#FF5722" },
];
